apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: gm21f1zr9-python
  janus-idp.io/tekton: gm21f1zr9-python
  backstage.io/kubernetes-id: gm21f1zr9-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: gm21f1zr9-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
