apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: gm21f1zr9-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-python:316dfb778ff543e204a12f12ed157a8e97aa9d05@sha256:596a2610ed90c3bdd5cbdcf62fe6a9821260588a47e8eedade050df09da4194e
          name: container-image
